apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argo-multiverse-labs/argoconeu26.git
    targetRevision: main
    path: tenants/tenant-a
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
