apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/tenant-template
  - project.yaml
  - rbac.yaml
  - network-policies.yaml

namespace: tenant-b

commonLabels:
  tenant: tenant-b

patches:
  - target:
      kind: Namespace
      name: tenant-template
    patch: |
      - op: replace
        path: /metadata/name
        value: tenant-b
  - target:
      kind: ServiceAccount
      name: sa-tenant-template
    patch: |
      - op: replace
        path: /metadata/name
        value: sa-tenant-b
  - target:
      kind: RoleBinding
      name: tenant-role-binding
    patch: |
      - op: replace
        path: /subjects/0/name
        value: sa-tenant-b
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: sa-tenant-b
  - target:
      kind: Pod
      name: curl-client
    patch: |
      - op: replace
        path: /spec/serviceAccountName
        value: sa-tenant-b
